# Generated by Django 4.2.14 on 2024-08-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='seller_offe',
            new_name='seller_offer',
        ),
    ]
